# Generated by Django 3.2 on 2022-12-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PanCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_url', models.URLField(max_length=500)),
                ('pan_details', models.CharField(max_length=250)),
            ],
        ),
    ]
